# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SZStorage' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SZStorage
pod 'YYKit', '~> 1.0.9'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'Masonry', '~> 1.0.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'UMengUShare/Social/WeChat'

end
